# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tjlik\Desktop\playerU.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from res_rc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 599)

        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        #mainWidget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #backgroundWidget
        self.backgroundWidget = QtWidgets.QWidget(self.centralwidget)
        self.backgroundWidget.setGeometry(QtCore.QRect(10, 10, 1101, 581))
        self.backgroundWidget.setStyleSheet(
                "QWidget#backgroundWidget{\n"
                "border-image: url(:/images/background.jpg);\n"
                "border-radius: 20px;\n"
                "}")
        self.backgroundWidget.setObjectName("backgroundWidget")

        #playWidget
        self.playWidget = QtWidgets.QWidget(self.backgroundWidget)
        self.playWidget.setGeometry(QtCore.QRect(30, 430, 311, 81))
        self.playWidget.setStyleSheet(
                "QWidget#playWidget {\n"
                "background-color: rgba(255, 255, 255, 100);\n"
                "border-radius: 10px;\n"
                "}")
        self.playWidget.setObjectName("playWidget")

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.playWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 311, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        #prevPushButton
        self.prevPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.prevPushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.prevPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.prevPushButton.setStyleSheet(
                "QPushButton{\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "image: url(:/images/prev.png);\n"
                "}\n"
                "QPushButton:hover{\n"
                "image: url(:/images/prevHover.png);\n"
                "}\n"
                "QPushButton:pressed{\n"
                "image: url(:/images/prevPressed.png);\n"
                "}")

        self.prevPushButton.setText("")
        self.prevPushButton.setObjectName("prevPushButton")

        self.horizontalLayout.addWidget(self.prevPushButton)

        #playPushButton
        self.playPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.playPushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.playPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.playPushButton.setStyleSheet(
                "QPushButton{\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "image: url(:/images/play.png);\n"
                "}\n"
                "QPushButton:hover{\n"
                "image: url(:/images/playHover.png);\n"
                "}\n"
                "QPushButton:pressed{\n"
                "image: url(:/images/playPressed.png);\n"
                "}")
        self.playPushButton.setText("")
        self.playPushButton.setObjectName("playPushButton")

        self.horizontalLayout.addWidget(self.playPushButton)

        #nextPushButton
        self.nextPushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextPushButton.setMinimumSize(QtCore.QSize(0, 60))
        self.nextPushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.nextPushButton.setStyleSheet(
                "QPushButton{\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "image: url(:/images/next.png);\n"
                "}\n"
                "QPushButton:hover{\n"
                "image: url(:/images/nextHover.png);\n"
                "}\n"
                "QPushButton:pressed{\n"
                "image: url(:/images/nextPressed.png);\n"
                "}")
        self.nextPushButton.setText("")
        self.nextPushButton.setObjectName("nextPushButton")

        self.horizontalLayout.addWidget(self.nextPushButton)

        #videoUrlLineEdit
        self.videoUrlLineEdit = QtWidgets.QLineEdit(self.backgroundWidget)
        self.videoUrlLineEdit.setGeometry(QtCore.QRect(390, 40, 581, 31))
        self.videoUrlLineEdit.setStyleSheet(
                "QLineEdit#videoUrlLineEdit{\n"
                "background-color: rgba(255, 255, 255, 100);\n"
                "border-radius: 10px;\n"
                "font-style: italic;\n"
                "}")
        self.videoUrlLineEdit.setObjectName("videoUrlLineEdit")

        #addPushButton
        self.addPushButton = QtWidgets.QPushButton(self.backgroundWidget)
        self.addPushButton.setGeometry(QtCore.QRect(980, 30, 101, 51))
        self.addPushButton.setStyleSheet(
                "QPushButton{\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "image: url(:/images/add.png);\n"
                "}\n"
                "QPushButton:hover{\n"
                "image: url(:/images/addHover.png);\n"
                "}\n"
                "QPushButton:pressed{\n"
                "image: url(:/images/addPressed.png);\n"
                "}")
        self.addPushButton.setText("")
        self.addPushButton.setObjectName("addPushButton")

        
        self.musicListWidget = QtWidgets.QListWidget(self.backgroundWidget)
        self.musicListWidget.setGeometry(QtCore.QRect(30, 30, 311, 381))
        self.musicListWidget.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;")
        self.musicListWidget.setObjectName("musicListWidget")
        self.horizontalSlider = QtWidgets.QSlider(self.backgroundWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 530, 311, 22))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal{\n"
"background-color: rgba(255, 255, 255, 100);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"width: 20px;\n"
"padding: 5px;\n"
"background-color: rgb(50, 150, 230);\n"
"border-radius: 10px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.videoUrlLineEdit.setInputMask(_translate("MainWindow", "URL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
